version: "3.9"
services:
  nodeapp1_c:
    build: .
    ports:
      - "4000:4000"
    links:
      - mongodb1
  mongodb1:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=molki
      - MONGO_INITDB_ROOT_PASSWORD=password